- Vagrantfile
Enabling file sharing
Configure the amount of memory for the VM to be 1024
#1
> Setting up Vagrant development environment box

- Pipfile
- Pipfile.lock
If apllied it will aoutomate the flake8 tool to check code that submitted to new PRs
> Updating Pipfile and Pipfile.lock

- Xpense/settings.py
- Xpense/urls.py
- main/admin.py
- main/apps.py
- main/templates/main/index.html
- main/tests.py
- main/views.py
using djangos views to render the welcome_page.html now only showing "coming soon"
> creating an initial structure for our app

- setup.sh
added setup command to automate the migration with the setup as instructed
> vagrant setup fix: wasnt migrating initially

- Xpense/settings.py
- expenses/apps.py
init expenses app
adding the app to the INSTALLED_APPS
#29
> Init expenses app

- Xpense/settings.py
- house/apps.py
- house/tests.py
adding the house app to the INSTALLED_APPS
Depends on PR #21
> Init house app

- Pipfile
- Pipfile.lock
- expenses/admin.py
- expenses/models.py
Add Expenses model and the category field
Here is how its looks in the admin panel:
✌✌✌
#30
> Expenses:  add category choice filed to the expenses model with init options

- .github/workflows/tests.yml
- Pipfile
- Pipfile.lock
- pytest.ini
> Pipeline: add tests to the Github action

- Pipfile
- Pipfile.lock
- Xpense/settings.py
- factories/house.py
- scripts/create_mock_data.py
installing django-extensions and factory_boy
The script creates a mock houses data with 500 items
to run the script on your computer run the following command:
python manage.py runscript create_mock_data
to add more scripts :
1. create a file in the scripts directory
2. define a function called run
3. write your code inside
relevant docomontatins: 
https://factoryboy.readthedocs.io/en/stable/index.html
https://django-extensions.readthedocs.io/en/latest/
> Data Mock: Add scripts to create mock data for our project

- Xpense/urls.py
- house/urls.py
- house/views.py
added dashboard + how to use with parameters from get request
added house_view view that get the house id and return the house information
added add_house api to add house with post request
we will need to add the Tips routing after the app will be marge
> Routing: Init routing the routing for the dashboard and the house view and form

- factories/expense.py
making the method `last_day_of_month` static fixes an error Im getting
and timedelta should be from timedate itself
> Mock Data: expenses mock data small fix

- Xpense/settings.py
- expenses/models.py
- factories/house.py
some linting using the 'black' formatter and checked with flake8
> General: linting and organizing

- house/constants.py
- house/views.py
- static/css/global.css
- templates/global/global.html
Initializing the global page 
creating three divs with css and html structure that will be the global page components 
the sidebar on the left
the table on the bottom
the charts in the top right
> Global Page: Create global page

- house/views.py
- static/css/global.css
- templates/global/filter_form.html
- templates/global/global.html
- templates/global/sidebar.html
- templates/global/table.html
> Global Page: Initializing the sidebar and table

- expenses/models.py
- expenses/test/test_expenses.py
- house/views.py
- static/css/chart.css
- static/css/global.css
- templates/global/chart.html
- templates/global/global.html
- tests/global_page_tests.py
Add the two charts to the global page
Filter options will be added in different PR
ChartJS: https://www.chartjs.org/docs/latest/
> Global page: Add Global page charts

- house/constants.py
- house/forms.py
- house/helpers.py
- house/tests/house_tests.py
- house/urls.py
- house/views.py
- static/css/form.css
- static/css/sidebar.css
- templates/global/city_dropdown.html
- templates/global/filter_form.html
- templates/global/sidebar.html
Added the Global page filter form
> Global Page: Add Global page filter form and filter logic

- Xpense/urls.py
- static/css/tips_board.css
- templates/base.html
- templates/tips/add_tip.html
- templates/tips/board.html
- templates/tips/edit_tip.html
- tips/constants.py
- tips/forms.py
- tips/tests/tips_views_tests.py
- tips/urls.py
- tips/views.py
> Tips views: create views for tips app

- house/constants.py
- house/forms.py
- house/tests/house_login_page_tests.py
- house/urls.py
- house/views.py
- static/css/login.css
- templates/base.html
- templates/login/login.html
- Checking if the house_id provided by the User exists in the database.
- If it does, redirecting to the appropriate Mine page
- Else, redirecting to Login page with an error message
(Tests included)
Screenshots:
Empty Form when a user enters the login page:
Successful match to a HouseID in the Database:
WrongID Error:
> House: Adding the Login Page

- house/helpers.py
- tests/house_tests.py
this way its filtering the profession of either parent and also makes this looks cleaner
> House Filter: refactor profession filtering

- static/js/bar_chart.js
- static/js/pie_chart.js
- static/js/random_colors.js
- templates/global/chart.html
- templates/tips/add_tip.html
- templates/tips/edit_tip.html
using django static files importing Im using the pie, bar, randomColors as external js files.
the pie_chart.js file needs the two variables
1) "randomColors" on window which will be an array of randomColors.
same in bar_char.js
2) both need a variable to tell them the relevant canvas Id.
window.pie_chart = "{canvas1_id}"
window.bar_chart ="{canvas2_id}"
> Chart: exported chart logic to external file

- static/js/bar_chart.js
- static/js/pie_chart.js
- templates/global/chart.html
This made the charts use of them be more customizable to show and to use more generically with params to the create functions.
> Charts: refactored the use of charts from the js files

- house/constants.py
- static/css/home.css
- static/js/home.js
- templates/home.html
- templates/home/home.html
https://user-images.githubusercontent.com/34008861/170483429-1e30c1d4-0af5-4970-8225-8dd202fce0ed.mp4
> Home Page: Create a smooth scrolling home page
